language: node_js
node_js:
  - "stable"

notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  - npm run build

after_success:
  - zip -r build.zip build/

before_deploy:
  - git config --local user.name Maurice Yap
  - git config --local user.email mauriceyap@hotmail.co.uk
  - git tag -d latest
  - export TRAVIS_TAG=latest
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $github_token
  file: build.zip
  skip_cleanup: true
  overwrite: true
  target_commitish: $TRAVIS_BRANCH
  on:
    tags: false
    branches:
      only:
      - master
