language: node_js
node_js:
  - "stable"

notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  - yarn build

after_success:
  - zip -r build.zip build/

deploy:
  provider: releases
  api_key: $github_token
  file: build.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
