language: node_js
node_js:
  - "stable"

notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  - npm run build

after_success:
  - zip -r build.zip build/
  - git tag -d latest ; git tag latest

deploy:
  provider: releases
  api_key: $github_token
  file: build.zip
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branches:
      only:
      - master
