export const WEBSOCKET_ADDRESS = `ws://${window.location.hostname}:2697/ws`;
export const WEBSOCKET_RECONNECT_INTERVAL = 2000;

export const HTTP_SERVER_BASE_ADDRESS = `http://${window.location.hostname}:2697`;

export const INITIAL_NETWORK_TOPOLOGY_LANGUAGE = "YAML";

export const SimulationStateEnum = {
  UNINITIALISED: "UNINITIALISED",
  INITIALISING: "INITIALISING",
  CREATING_VIRTUAL_NETWORK: "CREATING_VIRTUAL_NETWORK",
  CREATING_PROGRAM_IMAGES: "CREATING_PROGRAM_IMAGES",
  CREATING_NODES: "CREATING_NODES",
  READY_TO_RUN: "READY_TO_RUN",
  RUNNING: "RUNNING",
  RESETTING: "RESETTING"
};
